version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - 27017:27017
  graphql-server:
    build:
      context: './'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    environment:
      - mongoURI=mongodb://mongodb:27017/dao-api
